# Generated by Django 2.2.7 on 2019-12-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontypeb',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
