# Generated by Django 3.0.2 on 2020-02-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categoryquestion',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='categoryquestion',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solution',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='solutionquestion',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='solutionquestion',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
