# Generated by Django 2.2.7 on 2019-11-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontypeb',
            name='boolean_choice',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='questiontypeb',
            name='multiple_choice',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='questiontypeb',
            name='question_type',
            field=models.CharField(choices=[('IN', 'Integer'), ('BO', 'Boolean'), ('MC', 'Multiple Choice')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='questiontypeb',
            name='max_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questiontypeb',
            name='min_value',
            field=models.IntegerField(null=True),
        ),
    ]
