# Generated by Django 2.2.7 on 2019-12-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questiontypeb_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontypeb',
            name='argument',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('LOWER', 'Lower'), ('GREATER', 'Greater')], default='EQUAL', max_length=10),
        ),
    ]
